#!/usr/bin/env python
"""Render report_bm/report.md -> report_bm/report.html using template.html.

Bone-marrow variant of analysis/09_render_report.py (which renders the
lymph-node report under result/report/).  Everything is identical except the
input/output folder (result/report_bm) and the subtitle/footer text.
"""
from __future__ import annotations

import re
import sys
from html import escape
from pathlib import Path

try:
    import markdown as md
except ImportError:
    print("pip install markdown  (uv pip install markdown)", file=sys.stderr)
    sys.exit(1)

REPO = Path(__file__).resolve().parent.parent
REPORT = REPO / "result" / "report_bm"


def split_sections(md_text: str) -> list[tuple[str, str]]:
    """Group markdown into (title, html) per top-level heading block."""
    md_text = md_text.strip()
    parts = re.split(r"\n(?=#{1,2} )", md_text)
    sections = []
    for part in parts:
        lines = part.strip().split("\n")
        title = lines[0]
        title = re.sub(r"^#{1,2}\s+", "", title).strip()
        body = "\n".join(lines[1:]).strip()
        sections.append((title, body))
    return sections


def inline_md(body: str) -> str:
    html = md.markdown(
        body,
        extensions=["tables", "fenced_code", "sane_lists", "nl2br"],
    )
    html = html.replace('src="assets/', 'src="./assets/')
    return html


def main() -> None:
    md_text = (REPORT / "report.md").read_text(encoding="utf-8")
    template = (REPORT / "template.html").read_text(encoding="utf-8")

    title = md_text.split("\n")[0].lstrip("# ").strip()
    meta_lines = []
    for ln in md_text.split("\n"):
        if ln.startswith("- ") and "：" in ln:
            k, v = ln[2:].split("：", 1)
            meta_lines.append(f'<span class="chip">{escape(k)}：{escape(v)}</span>')

    sections = split_sections(md_text)
    tab_buttons = []
    panels = []
    for i, (t, body) in enumerate(sections):
        tab_buttons.append(f'<button class="tab" data-i="{i}">{escape(t)}</button>')
        inner = inline_md(body) if body else ""
        panels.append(f'<section class="panel" data-i="{i}">{inner}</section>')

    html = template
    html = html.replace("{{TITLE}}", escape(title))
    html = html.replace("{{SUBTITLE}}", escape(
        "Geneformer in silico perturbation for early PD detection (bone marrow)"))
    html = html.replace("{{META_CHIPS}}", "".join(meta_lines))
    html = html.replace("{{TAB_BUTTONS}}", "".join(tab_buttons))
    html = html.replace("{{PANELS}}", "".join(panels))
    html = html.replace("{{FOOTER}}", "Generated by analysis/09b_render_report_bm.py · Geneformer PD-BM ISP report")

    out = REPORT / "report.html"
    out.write_text(html, encoding="utf-8")
    print("wrote:", out)


if __name__ == "__main__":
    main()