#!/usr/bin/env python
"""Render report.md -> report.html using template.html.

Converts GitHub-flavored Markdown to HTML, splits the document into tabbed
sections (one tab per top-level '# ' / '## ' block group), and injects the
result into the template. Figures (images) under assets/ are linked relative to
the report folder so they render when the HTML is opened.

Usage:
  .venv/bin/python analysis/09c_render_report_blood.py
"""
from __future__ import annotations

import re
import sys
from html import escape
from pathlib import Path

try:
    import markdown as md
except ImportError:
    print("pip install markdown  (uv pip install markdown)", file=sys.stderr)
    sys.exit(1)

REPO = Path(__file__).resolve().parent.parent
REPORT = REPO / "result" / "report_blood"


def _inline(s: str) -> str:
    s = re.sub(r"`([^`]+)`", r"<code>\1</code>", s)
    s = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", s)
    s = re.sub(r"\*([^*]+)\*", r"<em>\1</em>", s)
    return s


def split_sections(md_text: str) -> list[tuple[str, str]]:
    """Group markdown into (title, html) per top-level heading block."""
    md_text = md_text.strip()
    # split on lines that are '# ' or '## '
    parts = re.split(r"\n(?=#{1,2} )", md_text)
    sections = []
    for part in parts:
        lines = part.strip().split("\n")
        title = lines[0]
        title = re.sub(r"^#{1,2}\s+", "", title).strip()
        body = "\n".join(lines[1:]).strip()
        # keep the heading for inside-tab context only if it is a top '#' (h1)
        sections.append((title, body))
    return sections


def inline_md(body: str) -> str:
    # convert markdown tables to HTML, code fences, lists, etc. via 'markdown'
    html = md.markdown(
        body,
        extensions=["tables", "fenced_code", "sane_lists", "nl2br"],
    )
    # images pointing at ./assets -> assets/
    html = html.replace('src="assets/', 'src="./assets/')
    return html


def main() -> None:
    md_text = (REPORT / "report.md").read_text(encoding="utf-8")
    template = (REPORT / "template.html").read_text(encoding="utf-8")

    # header / meta
    title = md_text.split("\n")[0].lstrip("# ").strip()
    # collect meta chips only from the metadata block (between the H1 and the
    # first horizontal rule '---'); avoids grabbing every bold list item.
    meta_lines = []
    for ln in md_text.split("\n")[1:]:
        if ln.startswith("---"):
            break
        if ln.startswith("- ") and "：" in ln:
            k, v = ln[2:].split("：", 1)
            meta_lines.append(f'<span class="chip">{escape(k)}：{escape(v)}</span>')

    # tabs
    sections = split_sections(md_text)
    # first (h1) becomes header context; drop if it repeats the title
    tab_buttons = []
    panels = []
    for i, (t, body) in enumerate(sections):
        tab_buttons.append(f'<button class="tab" data-i="{i}">{escape(t)}</button>')
        inner = inline_md(body) if body else ""
        panels.append(f'<section class="panel" data-i="{i}">{inner}</section>')

    # title: use first h1, subtitle = short
    subtitle = "Geneformer in silico perturbation for early PD detection (blood)"
    html = template
    html = html.replace("{{TITLE}}", escape(title))
    html = html.replace("{{SUBTITLE}}", escape(subtitle))
    html = html.replace("{{META_CHIPS}}", "".join(meta_lines))
    html = html.replace("{{TAB_BUTTONS}}", "".join(tab_buttons))
    html = html.replace("{{PANELS}}", "".join(panels))
    html = html.replace("{{FOOTER}}", "Generated by analysis/09c_render_report_blood.py · Geneformer PD-blood ISP report")

    out = REPORT / "report.html"
    out.write_text(html, encoding="utf-8")
    print("wrote:", out)


if __name__ == "__main__":
    main()